/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsOfServiceRouteImport } from './routes/terms-of-service'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as PrivacyPolicyRouteImport } from './routes/privacy-policy'
import { Route as IndustriesRouteImport } from './routes/industries'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CaseStudiesRouteImport } from './routes/case-studies'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ServicesWebAppDevelopmentRouteImport } from './routes/services.web-app-development'
import { Route as ServicesSaasDevelopmentRouteImport } from './routes/services.saas-development'
import { Route as ServicesMvpDevelopmentRouteImport } from './routes/services.mvp-development'
import { Route as ServicesMobileAppDevelopmentRouteImport } from './routes/services.mobile-app-development'
import { Route as ServicesCustomWebsiteDevelopmentRouteImport } from './routes/services.custom-website-development'
import { Route as ServicesCustomSoftwareDevelopmentRouteImport } from './routes/services.custom-software-development'
import { Route as ApiSendEmailRouteImport } from './routes/api.send-email'

const TermsOfServiceRoute = TermsOfServiceRouteImport.update({
  id: '/terms-of-service',
  path: '/terms-of-service',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyPolicyRoute = PrivacyPolicyRouteImport.update({
  id: '/privacy-policy',
  path: '/privacy-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const IndustriesRoute = IndustriesRouteImport.update({
  id: '/industries',
  path: '/industries',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CaseStudiesRoute = CaseStudiesRouteImport.update({
  id: '/case-studies',
  path: '/case-studies',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesWebAppDevelopmentRoute =
  ServicesWebAppDevelopmentRouteImport.update({
    id: '/services/web-app-development',
    path: '/services/web-app-development',
    getParentRoute: () => rootRouteImport,
  } as any)
const ServicesSaasDevelopmentRoute = ServicesSaasDevelopmentRouteImport.update({
  id: '/services/saas-development',
  path: '/services/saas-development',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesMvpDevelopmentRoute = ServicesMvpDevelopmentRouteImport.update({
  id: '/services/mvp-development',
  path: '/services/mvp-development',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesMobileAppDevelopmentRoute =
  ServicesMobileAppDevelopmentRouteImport.update({
    id: '/services/mobile-app-development',
    path: '/services/mobile-app-development',
    getParentRoute: () => rootRouteImport,
  } as any)
const ServicesCustomWebsiteDevelopmentRoute =
  ServicesCustomWebsiteDevelopmentRouteImport.update({
    id: '/services/custom-website-development',
    path: '/services/custom-website-development',
    getParentRoute: () => rootRouteImport,
  } as any)
const ServicesCustomSoftwareDevelopmentRoute =
  ServicesCustomSoftwareDevelopmentRouteImport.update({
    id: '/services/custom-software-development',
    path: '/services/custom-software-development',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiSendEmailRoute = ApiSendEmailRouteImport.update({
  id: '/api/send-email',
  path: '/api/send-email',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/case-studies': typeof CaseStudiesRoute
  '/contact': typeof ContactRoute
  '/industries': typeof IndustriesRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms-of-service': typeof TermsOfServiceRoute
  '/api/send-email': typeof ApiSendEmailRoute
  '/services/custom-software-development': typeof ServicesCustomSoftwareDevelopmentRoute
  '/services/custom-website-development': typeof ServicesCustomWebsiteDevelopmentRoute
  '/services/mobile-app-development': typeof ServicesMobileAppDevelopmentRoute
  '/services/mvp-development': typeof ServicesMvpDevelopmentRoute
  '/services/saas-development': typeof ServicesSaasDevelopmentRoute
  '/services/web-app-development': typeof ServicesWebAppDevelopmentRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/case-studies': typeof CaseStudiesRoute
  '/contact': typeof ContactRoute
  '/industries': typeof IndustriesRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms-of-service': typeof TermsOfServiceRoute
  '/api/send-email': typeof ApiSendEmailRoute
  '/services/custom-software-development': typeof ServicesCustomSoftwareDevelopmentRoute
  '/services/custom-website-development': typeof ServicesCustomWebsiteDevelopmentRoute
  '/services/mobile-app-development': typeof ServicesMobileAppDevelopmentRoute
  '/services/mvp-development': typeof ServicesMvpDevelopmentRoute
  '/services/saas-development': typeof ServicesSaasDevelopmentRoute
  '/services/web-app-development': typeof ServicesWebAppDevelopmentRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/case-studies': typeof CaseStudiesRoute
  '/contact': typeof ContactRoute
  '/industries': typeof IndustriesRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms-of-service': typeof TermsOfServiceRoute
  '/api/send-email': typeof ApiSendEmailRoute
  '/services/custom-software-development': typeof ServicesCustomSoftwareDevelopmentRoute
  '/services/custom-website-development': typeof ServicesCustomWebsiteDevelopmentRoute
  '/services/mobile-app-development': typeof ServicesMobileAppDevelopmentRoute
  '/services/mvp-development': typeof ServicesMvpDevelopmentRoute
  '/services/saas-development': typeof ServicesSaasDevelopmentRoute
  '/services/web-app-development': typeof ServicesWebAppDevelopmentRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/case-studies'
    | '/contact'
    | '/industries'
    | '/privacy-policy'
    | '/sitemap.xml'
    | '/terms-of-service'
    | '/api/send-email'
    | '/services/custom-software-development'
    | '/services/custom-website-development'
    | '/services/mobile-app-development'
    | '/services/mvp-development'
    | '/services/saas-development'
    | '/services/web-app-development'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/case-studies'
    | '/contact'
    | '/industries'
    | '/privacy-policy'
    | '/sitemap.xml'
    | '/terms-of-service'
    | '/api/send-email'
    | '/services/custom-software-development'
    | '/services/custom-website-development'
    | '/services/mobile-app-development'
    | '/services/mvp-development'
    | '/services/saas-development'
    | '/services/web-app-development'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/case-studies'
    | '/contact'
    | '/industries'
    | '/privacy-policy'
    | '/sitemap.xml'
    | '/terms-of-service'
    | '/api/send-email'
    | '/services/custom-software-development'
    | '/services/custom-website-development'
    | '/services/mobile-app-development'
    | '/services/mvp-development'
    | '/services/saas-development'
    | '/services/web-app-development'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  CaseStudiesRoute: typeof CaseStudiesRoute
  ContactRoute: typeof ContactRoute
  IndustriesRoute: typeof IndustriesRoute
  PrivacyPolicyRoute: typeof PrivacyPolicyRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TermsOfServiceRoute: typeof TermsOfServiceRoute
  ApiSendEmailRoute: typeof ApiSendEmailRoute
  ServicesCustomSoftwareDevelopmentRoute: typeof ServicesCustomSoftwareDevelopmentRoute
  ServicesCustomWebsiteDevelopmentRoute: typeof ServicesCustomWebsiteDevelopmentRoute
  ServicesMobileAppDevelopmentRoute: typeof ServicesMobileAppDevelopmentRoute
  ServicesMvpDevelopmentRoute: typeof ServicesMvpDevelopmentRoute
  ServicesSaasDevelopmentRoute: typeof ServicesSaasDevelopmentRoute
  ServicesWebAppDevelopmentRoute: typeof ServicesWebAppDevelopmentRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms-of-service': {
      id: '/terms-of-service'
      path: '/terms-of-service'
      fullPath: '/terms-of-service'
      preLoaderRoute: typeof TermsOfServiceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy-policy': {
      id: '/privacy-policy'
      path: '/privacy-policy'
      fullPath: '/privacy-policy'
      preLoaderRoute: typeof PrivacyPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/industries': {
      id: '/industries'
      path: '/industries'
      fullPath: '/industries'
      preLoaderRoute: typeof IndustriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/case-studies': {
      id: '/case-studies'
      path: '/case-studies'
      fullPath: '/case-studies'
      preLoaderRoute: typeof CaseStudiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/web-app-development': {
      id: '/services/web-app-development'
      path: '/services/web-app-development'
      fullPath: '/services/web-app-development'
      preLoaderRoute: typeof ServicesWebAppDevelopmentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/saas-development': {
      id: '/services/saas-development'
      path: '/services/saas-development'
      fullPath: '/services/saas-development'
      preLoaderRoute: typeof ServicesSaasDevelopmentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/mvp-development': {
      id: '/services/mvp-development'
      path: '/services/mvp-development'
      fullPath: '/services/mvp-development'
      preLoaderRoute: typeof ServicesMvpDevelopmentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/mobile-app-development': {
      id: '/services/mobile-app-development'
      path: '/services/mobile-app-development'
      fullPath: '/services/mobile-app-development'
      preLoaderRoute: typeof ServicesMobileAppDevelopmentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/custom-website-development': {
      id: '/services/custom-website-development'
      path: '/services/custom-website-development'
      fullPath: '/services/custom-website-development'
      preLoaderRoute: typeof ServicesCustomWebsiteDevelopmentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/custom-software-development': {
      id: '/services/custom-software-development'
      path: '/services/custom-software-development'
      fullPath: '/services/custom-software-development'
      preLoaderRoute: typeof ServicesCustomSoftwareDevelopmentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/send-email': {
      id: '/api/send-email'
      path: '/api/send-email'
      fullPath: '/api/send-email'
      preLoaderRoute: typeof ApiSendEmailRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  CaseStudiesRoute: CaseStudiesRoute,
  ContactRoute: ContactRoute,
  IndustriesRoute: IndustriesRoute,
  PrivacyPolicyRoute: PrivacyPolicyRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TermsOfServiceRoute: TermsOfServiceRoute,
  ApiSendEmailRoute: ApiSendEmailRoute,
  ServicesCustomSoftwareDevelopmentRoute:
    ServicesCustomSoftwareDevelopmentRoute,
  ServicesCustomWebsiteDevelopmentRoute: ServicesCustomWebsiteDevelopmentRoute,
  ServicesMobileAppDevelopmentRoute: ServicesMobileAppDevelopmentRoute,
  ServicesMvpDevelopmentRoute: ServicesMvpDevelopmentRoute,
  ServicesSaasDevelopmentRoute: ServicesSaasDevelopmentRoute,
  ServicesWebAppDevelopmentRoute: ServicesWebAppDevelopmentRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
